name: Build Zorva APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir:.
          buildozer_version: stable
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Zorva-APK
          path:./bin/*.apk
